### ISSUE TITLE
戴我好，我发现一个超级无敌的bug

### ISSUE THREAD

**Issue by hanghang0702** [yonggandewo/ToLive#1]
# **在挖矿或者战斗的时候只要选择一把自己没有的剑就可以免除怪物伤害！！！！**
@yonggandewo

**Comment by yonggandewo** [comment]
## 您好！首先感谢您的反馈，以下为回复：
v0.1.1及以前有伤害但无提示信息，v0.1.2及以后已加入提示信息
@hanghang0702
